# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['PolicyReputationArgs', 'PolicyReputation']

@pulumi.input_type
class PolicyReputationArgs:
    def __init__(__self__, *,
                 check_ip: Optional[pulumi.Input[bool]] = None,
                 check_username: Optional[pulumi.Input[bool]] = None,
                 execution_logging: Optional[pulumi.Input[bool]] = None,
                 name: Optional[pulumi.Input[str]] = None,
                 policy_reputation_id: Optional[pulumi.Input[str]] = None,
                 threshold: Optional[pulumi.Input[float]] = None):
        """
        The set of arguments for constructing a PolicyReputation resource.
        :param pulumi.Input[bool] check_ip: Defaults to `true`.
        :param pulumi.Input[bool] check_username: Defaults to `true`.
        :param pulumi.Input[bool] execution_logging: Defaults to `false`.
        :param pulumi.Input[float] threshold: Defaults to `10`.
        """
        if check_ip is not None:
            pulumi.set(__self__, "check_ip", check_ip)
        if check_username is not None:
            pulumi.set(__self__, "check_username", check_username)
        if execution_logging is not None:
            pulumi.set(__self__, "execution_logging", execution_logging)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if policy_reputation_id is not None:
            pulumi.set(__self__, "policy_reputation_id", policy_reputation_id)
        if threshold is not None:
            pulumi.set(__self__, "threshold", threshold)

    @property
    @pulumi.getter(name="checkIp")
    def check_ip(self) -> Optional[pulumi.Input[bool]]:
        """
        Defaults to `true`.
        """
        return pulumi.get(self, "check_ip")

    @check_ip.setter
    def check_ip(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "check_ip", value)

    @property
    @pulumi.getter(name="checkUsername")
    def check_username(self) -> Optional[pulumi.Input[bool]]:
        """
        Defaults to `true`.
        """
        return pulumi.get(self, "check_username")

    @check_username.setter
    def check_username(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "check_username", value)

    @property
    @pulumi.getter(name="executionLogging")
    def execution_logging(self) -> Optional[pulumi.Input[bool]]:
        """
        Defaults to `false`.
        """
        return pulumi.get(self, "execution_logging")

    @execution_logging.setter
    def execution_logging(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "execution_logging", value)

    @property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[str]]:
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "name", value)

    @property
    @pulumi.getter(name="policyReputationId")
    def policy_reputation_id(self) -> Optional[pulumi.Input[str]]:
        return pulumi.get(self, "policy_reputation_id")

    @policy_reputation_id.setter
    def policy_reputation_id(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "policy_reputation_id", value)

    @property
    @pulumi.getter
    def threshold(self) -> Optional[pulumi.Input[float]]:
        """
        Defaults to `10`.
        """
        return pulumi.get(self, "threshold")

    @threshold.setter
    def threshold(self, value: Optional[pulumi.Input[float]]):
        pulumi.set(self, "threshold", value)


@pulumi.input_type
class _PolicyReputationState:
    def __init__(__self__, *,
                 check_ip: Optional[pulumi.Input[bool]] = None,
                 check_username: Optional[pulumi.Input[bool]] = None,
                 execution_logging: Optional[pulumi.Input[bool]] = None,
                 name: Optional[pulumi.Input[str]] = None,
                 policy_reputation_id: Optional[pulumi.Input[str]] = None,
                 threshold: Optional[pulumi.Input[float]] = None):
        """
        Input properties used for looking up and filtering PolicyReputation resources.
        :param pulumi.Input[bool] check_ip: Defaults to `true`.
        :param pulumi.Input[bool] check_username: Defaults to `true`.
        :param pulumi.Input[bool] execution_logging: Defaults to `false`.
        :param pulumi.Input[float] threshold: Defaults to `10`.
        """
        if check_ip is not None:
            pulumi.set(__self__, "check_ip", check_ip)
        if check_username is not None:
            pulumi.set(__self__, "check_username", check_username)
        if execution_logging is not None:
            pulumi.set(__self__, "execution_logging", execution_logging)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if policy_reputation_id is not None:
            pulumi.set(__self__, "policy_reputation_id", policy_reputation_id)
        if threshold is not None:
            pulumi.set(__self__, "threshold", threshold)

    @property
    @pulumi.getter(name="checkIp")
    def check_ip(self) -> Optional[pulumi.Input[bool]]:
        """
        Defaults to `true`.
        """
        return pulumi.get(self, "check_ip")

    @check_ip.setter
    def check_ip(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "check_ip", value)

    @property
    @pulumi.getter(name="checkUsername")
    def check_username(self) -> Optional[pulumi.Input[bool]]:
        """
        Defaults to `true`.
        """
        return pulumi.get(self, "check_username")

    @check_username.setter
    def check_username(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "check_username", value)

    @property
    @pulumi.getter(name="executionLogging")
    def execution_logging(self) -> Optional[pulumi.Input[bool]]:
        """
        Defaults to `false`.
        """
        return pulumi.get(self, "execution_logging")

    @execution_logging.setter
    def execution_logging(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "execution_logging", value)

    @property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[str]]:
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "name", value)

    @property
    @pulumi.getter(name="policyReputationId")
    def policy_reputation_id(self) -> Optional[pulumi.Input[str]]:
        return pulumi.get(self, "policy_reputation_id")

    @policy_reputation_id.setter
    def policy_reputation_id(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "policy_reputation_id", value)

    @property
    @pulumi.getter
    def threshold(self) -> Optional[pulumi.Input[float]]:
        """
        Defaults to `10`.
        """
        return pulumi.get(self, "threshold")

    @threshold.setter
    def threshold(self, value: Optional[pulumi.Input[float]]):
        pulumi.set(self, "threshold", value)


class PolicyReputation(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 check_ip: Optional[pulumi.Input[bool]] = None,
                 check_username: Optional[pulumi.Input[bool]] = None,
                 execution_logging: Optional[pulumi.Input[bool]] = None,
                 name: Optional[pulumi.Input[str]] = None,
                 policy_reputation_id: Optional[pulumi.Input[str]] = None,
                 threshold: Optional[pulumi.Input[float]] = None,
                 __props__=None):
        """
        Create a PolicyReputation resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[bool] check_ip: Defaults to `true`.
        :param pulumi.Input[bool] check_username: Defaults to `true`.
        :param pulumi.Input[bool] execution_logging: Defaults to `false`.
        :param pulumi.Input[float] threshold: Defaults to `10`.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: Optional[PolicyReputationArgs] = None,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a PolicyReputation resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param PolicyReputationArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(PolicyReputationArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 check_ip: Optional[pulumi.Input[bool]] = None,
                 check_username: Optional[pulumi.Input[bool]] = None,
                 execution_logging: Optional[pulumi.Input[bool]] = None,
                 name: Optional[pulumi.Input[str]] = None,
                 policy_reputation_id: Optional[pulumi.Input[str]] = None,
                 threshold: Optional[pulumi.Input[float]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = PolicyReputationArgs.__new__(PolicyReputationArgs)

            __props__.__dict__["check_ip"] = check_ip
            __props__.__dict__["check_username"] = check_username
            __props__.__dict__["execution_logging"] = execution_logging
            __props__.__dict__["name"] = name
            __props__.__dict__["policy_reputation_id"] = policy_reputation_id
            __props__.__dict__["threshold"] = threshold
        super(PolicyReputation, __self__).__init__(
            'authentik:index/policyReputation:PolicyReputation',
            resource_name,
            __props__,
            opts,
            package_ref=_utilities.get_package())

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            check_ip: Optional[pulumi.Input[bool]] = None,
            check_username: Optional[pulumi.Input[bool]] = None,
            execution_logging: Optional[pulumi.Input[bool]] = None,
            name: Optional[pulumi.Input[str]] = None,
            policy_reputation_id: Optional[pulumi.Input[str]] = None,
            threshold: Optional[pulumi.Input[float]] = None) -> 'PolicyReputation':
        """
        Get an existing PolicyReputation resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[bool] check_ip: Defaults to `true`.
        :param pulumi.Input[bool] check_username: Defaults to `true`.
        :param pulumi.Input[bool] execution_logging: Defaults to `false`.
        :param pulumi.Input[float] threshold: Defaults to `10`.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _PolicyReputationState.__new__(_PolicyReputationState)

        __props__.__dict__["check_ip"] = check_ip
        __props__.__dict__["check_username"] = check_username
        __props__.__dict__["execution_logging"] = execution_logging
        __props__.__dict__["name"] = name
        __props__.__dict__["policy_reputation_id"] = policy_reputation_id
        __props__.__dict__["threshold"] = threshold
        return PolicyReputation(resource_name, opts=opts, __props__=__props__)

    @property
    @pulumi.getter(name="checkIp")
    def check_ip(self) -> pulumi.Output[Optional[bool]]:
        """
        Defaults to `true`.
        """
        return pulumi.get(self, "check_ip")

    @property
    @pulumi.getter(name="checkUsername")
    def check_username(self) -> pulumi.Output[Optional[bool]]:
        """
        Defaults to `true`.
        """
        return pulumi.get(self, "check_username")

    @property
    @pulumi.getter(name="executionLogging")
    def execution_logging(self) -> pulumi.Output[Optional[bool]]:
        """
        Defaults to `false`.
        """
        return pulumi.get(self, "execution_logging")

    @property
    @pulumi.getter
    def name(self) -> pulumi.Output[str]:
        return pulumi.get(self, "name")

    @property
    @pulumi.getter(name="policyReputationId")
    def policy_reputation_id(self) -> pulumi.Output[str]:
        return pulumi.get(self, "policy_reputation_id")

    @property
    @pulumi.getter
    def threshold(self) -> pulumi.Output[Optional[float]]:
        """
        Defaults to `10`.
        """
        return pulumi.get(self, "threshold")

