# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['PropertyMappingProviderScopeArgs', 'PropertyMappingProviderScope']

@pulumi.input_type
class PropertyMappingProviderScopeArgs:
    def __init__(__self__, *,
                 expression: pulumi.Input[str],
                 scope_name: pulumi.Input[str],
                 description: Optional[pulumi.Input[str]] = None,
                 name: Optional[pulumi.Input[str]] = None,
                 property_mapping_provider_scope_id: Optional[pulumi.Input[str]] = None):
        """
        The set of arguments for constructing a PropertyMappingProviderScope resource.
        """
        pulumi.set(__self__, "expression", expression)
        pulumi.set(__self__, "scope_name", scope_name)
        if description is not None:
            pulumi.set(__self__, "description", description)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if property_mapping_provider_scope_id is not None:
            pulumi.set(__self__, "property_mapping_provider_scope_id", property_mapping_provider_scope_id)

    @property
    @pulumi.getter
    def expression(self) -> pulumi.Input[str]:
        return pulumi.get(self, "expression")

    @expression.setter
    def expression(self, value: pulumi.Input[str]):
        pulumi.set(self, "expression", value)

    @property
    @pulumi.getter(name="scopeName")
    def scope_name(self) -> pulumi.Input[str]:
        return pulumi.get(self, "scope_name")

    @scope_name.setter
    def scope_name(self, value: pulumi.Input[str]):
        pulumi.set(self, "scope_name", value)

    @property
    @pulumi.getter
    def description(self) -> Optional[pulumi.Input[str]]:
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "description", value)

    @property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[str]]:
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "name", value)

    @property
    @pulumi.getter(name="propertyMappingProviderScopeId")
    def property_mapping_provider_scope_id(self) -> Optional[pulumi.Input[str]]:
        return pulumi.get(self, "property_mapping_provider_scope_id")

    @property_mapping_provider_scope_id.setter
    def property_mapping_provider_scope_id(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "property_mapping_provider_scope_id", value)


@pulumi.input_type
class _PropertyMappingProviderScopeState:
    def __init__(__self__, *,
                 description: Optional[pulumi.Input[str]] = None,
                 expression: Optional[pulumi.Input[str]] = None,
                 name: Optional[pulumi.Input[str]] = None,
                 property_mapping_provider_scope_id: Optional[pulumi.Input[str]] = None,
                 scope_name: Optional[pulumi.Input[str]] = None):
        """
        Input properties used for looking up and filtering PropertyMappingProviderScope resources.
        """
        if description is not None:
            pulumi.set(__self__, "description", description)
        if expression is not None:
            pulumi.set(__self__, "expression", expression)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if property_mapping_provider_scope_id is not None:
            pulumi.set(__self__, "property_mapping_provider_scope_id", property_mapping_provider_scope_id)
        if scope_name is not None:
            pulumi.set(__self__, "scope_name", scope_name)

    @property
    @pulumi.getter
    def description(self) -> Optional[pulumi.Input[str]]:
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "description", value)

    @property
    @pulumi.getter
    def expression(self) -> Optional[pulumi.Input[str]]:
        return pulumi.get(self, "expression")

    @expression.setter
    def expression(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "expression", value)

    @property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[str]]:
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "name", value)

    @property
    @pulumi.getter(name="propertyMappingProviderScopeId")
    def property_mapping_provider_scope_id(self) -> Optional[pulumi.Input[str]]:
        return pulumi.get(self, "property_mapping_provider_scope_id")

    @property_mapping_provider_scope_id.setter
    def property_mapping_provider_scope_id(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "property_mapping_provider_scope_id", value)

    @property
    @pulumi.getter(name="scopeName")
    def scope_name(self) -> Optional[pulumi.Input[str]]:
        return pulumi.get(self, "scope_name")

    @scope_name.setter
    def scope_name(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "scope_name", value)


class PropertyMappingProviderScope(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 description: Optional[pulumi.Input[str]] = None,
                 expression: Optional[pulumi.Input[str]] = None,
                 name: Optional[pulumi.Input[str]] = None,
                 property_mapping_provider_scope_id: Optional[pulumi.Input[str]] = None,
                 scope_name: Optional[pulumi.Input[str]] = None,
                 __props__=None):
        """
        Create a PropertyMappingProviderScope resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: PropertyMappingProviderScopeArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a PropertyMappingProviderScope resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param PropertyMappingProviderScopeArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(PropertyMappingProviderScopeArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 description: Optional[pulumi.Input[str]] = None,
                 expression: Optional[pulumi.Input[str]] = None,
                 name: Optional[pulumi.Input[str]] = None,
                 property_mapping_provider_scope_id: Optional[pulumi.Input[str]] = None,
                 scope_name: Optional[pulumi.Input[str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = PropertyMappingProviderScopeArgs.__new__(PropertyMappingProviderScopeArgs)

            __props__.__dict__["description"] = description
            if expression is None and not opts.urn:
                raise TypeError("Missing required property 'expression'")
            __props__.__dict__["expression"] = expression
            __props__.__dict__["name"] = name
            __props__.__dict__["property_mapping_provider_scope_id"] = property_mapping_provider_scope_id
            if scope_name is None and not opts.urn:
                raise TypeError("Missing required property 'scope_name'")
            __props__.__dict__["scope_name"] = scope_name
        super(PropertyMappingProviderScope, __self__).__init__(
            'authentik:index/propertyMappingProviderScope:PropertyMappingProviderScope',
            resource_name,
            __props__,
            opts,
            package_ref=_utilities.get_package())

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            description: Optional[pulumi.Input[str]] = None,
            expression: Optional[pulumi.Input[str]] = None,
            name: Optional[pulumi.Input[str]] = None,
            property_mapping_provider_scope_id: Optional[pulumi.Input[str]] = None,
            scope_name: Optional[pulumi.Input[str]] = None) -> 'PropertyMappingProviderScope':
        """
        Get an existing PropertyMappingProviderScope resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _PropertyMappingProviderScopeState.__new__(_PropertyMappingProviderScopeState)

        __props__.__dict__["description"] = description
        __props__.__dict__["expression"] = expression
        __props__.__dict__["name"] = name
        __props__.__dict__["property_mapping_provider_scope_id"] = property_mapping_provider_scope_id
        __props__.__dict__["scope_name"] = scope_name
        return PropertyMappingProviderScope(resource_name, opts=opts, __props__=__props__)

    @property
    @pulumi.getter
    def description(self) -> pulumi.Output[Optional[str]]:
        return pulumi.get(self, "description")

    @property
    @pulumi.getter
    def expression(self) -> pulumi.Output[str]:
        return pulumi.get(self, "expression")

    @property
    @pulumi.getter
    def name(self) -> pulumi.Output[str]:
        return pulumi.get(self, "name")

    @property
    @pulumi.getter(name="propertyMappingProviderScopeId")
    def property_mapping_provider_scope_id(self) -> pulumi.Output[str]:
        return pulumi.get(self, "property_mapping_provider_scope_id")

    @property
    @pulumi.getter(name="scopeName")
    def scope_name(self) -> pulumi.Output[str]:
        return pulumi.get(self, "scope_name")

