# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['RbacPermissionUserArgs', 'RbacPermissionUser']

@pulumi.input_type
class RbacPermissionUserArgs:
    def __init__(__self__, *,
                 permission: pulumi.Input[str],
                 user: pulumi.Input[float],
                 model: Optional[pulumi.Input[str]] = None,
                 object_id: Optional[pulumi.Input[str]] = None,
                 rbac_permission_user_id: Optional[pulumi.Input[str]] = None):
        """
        The set of arguments for constructing a RbacPermissionUser resource.
        :param pulumi.Input[str] model: Allowed values: - `authentik_tenants.domain` - `authentik_crypto.certificatekeypair` - `authentik_flows.flow` -
               `authentik_flows.flowstagebinding` - `authentik_outposts.dockerserviceconnection` -
               `authentik_outposts.kubernetesserviceconnection` - `authentik_outposts.outpost` - `authentik_policies_dummy.dummypolicy`
               - `authentik_policies_event_matcher.eventmatcherpolicy` - `authentik_policies_expiry.passwordexpirypolicy` -
               `authentik_policies_expression.expressionpolicy` - `authentik_policies_geoip.geoippolicy` -
               `authentik_policies_password.passwordpolicy` - `authentik_policies_reputation.reputationpolicy` -
               `authentik_policies.policybinding` - `authentik_providers_ldap.ldapprovider` - `authentik_providers_oauth2.scopemapping`
               - `authentik_providers_oauth2.oauth2provider` - `authentik_providers_proxy.proxyprovider` -
               `authentik_providers_radius.radiusprovider` - `authentik_providers_radius.radiusproviderpropertymapping` -
               `authentik_providers_saml.samlprovider` - `authentik_providers_saml.samlpropertymapping` -
               `authentik_providers_scim.scimprovider` - `authentik_providers_scim.scimmapping` - `authentik_rbac.role` -
               `authentik_sources_kerberos.kerberossource` - `authentik_sources_kerberos.kerberossourcepropertymapping` -
               `authentik_sources_kerberos.userkerberossourceconnection` - `authentik_sources_kerberos.groupkerberossourceconnection` -
               `authentik_sources_ldap.ldapsource` - `authentik_sources_ldap.ldapsourcepropertymapping` -
               `authentik_sources_oauth.oauthsource` - `authentik_sources_oauth.oauthsourcepropertymapping` -
               `authentik_sources_oauth.useroauthsourceconnection` - `authentik_sources_oauth.groupoauthsourceconnection` -
               `authentik_sources_plex.plexsource` - `authentik_sources_plex.plexsourcepropertymapping` -
               `authentik_sources_plex.userplexsourceconnection` - `authentik_sources_plex.groupplexsourceconnection` -
               `authentik_sources_saml.samlsource` - `authentik_sources_saml.samlsourcepropertymapping` -
               `authentik_sources_saml.usersamlsourceconnection` - `authentik_sources_saml.groupsamlsourceconnection` -
               `authentik_sources_scim.scimsource` - `authentik_sources_scim.scimsourcepropertymapping` -
               `authentik_stages_authenticator_duo.authenticatorduostage` - `authentik_stages_authenticator_duo.duodevice` -
               `authentik_stages_authenticator_sms.authenticatorsmsstage` - `authentik_stages_authenticator_sms.smsdevice` -
               `authentik_stages_authenticator_static.authenticatorstaticstage` - `authentik_stages_authenticator_static.staticdevice`
               - `authentik_stages_authenticator_totp.authenticatortotpstage` - `authentik_stages_authenticator_totp.totpdevice` -
               `authentik_stages_authenticator_validate.authenticatorvalidatestage` -
               `authentik_stages_authenticator_webauthn.authenticatorwebauthnstage` -
               `authentik_stages_authenticator_webauthn.webauthndevice` - `authentik_stages_captcha.captchastage` -
               `authentik_stages_consent.consentstage` - `authentik_stages_consent.userconsent` - `authentik_stages_deny.denystage` -
               `authentik_stages_dummy.dummystage` - `authentik_stages_email.emailstage` -
               `authentik_stages_identification.identificationstage` - `authentik_stages_invitation.invitationstage` -
               `authentik_stages_invitation.invitation` - `authentik_stages_password.passwordstage` - `authentik_stages_prompt.prompt`
               - `authentik_stages_prompt.promptstage` - `authentik_stages_user_delete.userdeletestage` -
               `authentik_stages_user_login.userloginstage` - `authentik_stages_user_logout.userlogoutstage` -
               `authentik_stages_user_write.userwritestage` - `authentik_brands.brand` - `authentik_blueprints.blueprintinstance` -
               `authentik_core.group` - `authentik_core.user` - `authentik_core.application` - `authentik_core.token` -
               `authentik_enterprise.license` - `authentik_providers_google_workspace.googleworkspaceprovider` -
               `authentik_providers_google_workspace.googleworkspaceprovidermapping` -
               `authentik_providers_microsoft_entra.microsoftentraprovider` -
               `authentik_providers_microsoft_entra.microsoftentraprovidermapping` - `authentik_providers_rac.racprovider` -
               `authentik_providers_rac.endpoint` - `authentik_providers_rac.racpropertymapping` -
               `authentik_stages_authenticator_endpoint_gdtc.authenticatorendpointgdtcstage` - `authentik_stages_source.sourcestage` -
               `authentik_events.event` - `authentik_events.notificationtransport` - `authentik_events.notification` -
               `authentik_events.notificationrule` - `authentik_events.notificationwebhookmapping`
        """
        pulumi.set(__self__, "permission", permission)
        pulumi.set(__self__, "user", user)
        if model is not None:
            pulumi.set(__self__, "model", model)
        if object_id is not None:
            pulumi.set(__self__, "object_id", object_id)
        if rbac_permission_user_id is not None:
            pulumi.set(__self__, "rbac_permission_user_id", rbac_permission_user_id)

    @property
    @pulumi.getter
    def permission(self) -> pulumi.Input[str]:
        return pulumi.get(self, "permission")

    @permission.setter
    def permission(self, value: pulumi.Input[str]):
        pulumi.set(self, "permission", value)

    @property
    @pulumi.getter
    def user(self) -> pulumi.Input[float]:
        return pulumi.get(self, "user")

    @user.setter
    def user(self, value: pulumi.Input[float]):
        pulumi.set(self, "user", value)

    @property
    @pulumi.getter
    def model(self) -> Optional[pulumi.Input[str]]:
        """
        Allowed values: - `authentik_tenants.domain` - `authentik_crypto.certificatekeypair` - `authentik_flows.flow` -
        `authentik_flows.flowstagebinding` - `authentik_outposts.dockerserviceconnection` -
        `authentik_outposts.kubernetesserviceconnection` - `authentik_outposts.outpost` - `authentik_policies_dummy.dummypolicy`
        - `authentik_policies_event_matcher.eventmatcherpolicy` - `authentik_policies_expiry.passwordexpirypolicy` -
        `authentik_policies_expression.expressionpolicy` - `authentik_policies_geoip.geoippolicy` -
        `authentik_policies_password.passwordpolicy` - `authentik_policies_reputation.reputationpolicy` -
        `authentik_policies.policybinding` - `authentik_providers_ldap.ldapprovider` - `authentik_providers_oauth2.scopemapping`
        - `authentik_providers_oauth2.oauth2provider` - `authentik_providers_proxy.proxyprovider` -
        `authentik_providers_radius.radiusprovider` - `authentik_providers_radius.radiusproviderpropertymapping` -
        `authentik_providers_saml.samlprovider` - `authentik_providers_saml.samlpropertymapping` -
        `authentik_providers_scim.scimprovider` - `authentik_providers_scim.scimmapping` - `authentik_rbac.role` -
        `authentik_sources_kerberos.kerberossource` - `authentik_sources_kerberos.kerberossourcepropertymapping` -
        `authentik_sources_kerberos.userkerberossourceconnection` - `authentik_sources_kerberos.groupkerberossourceconnection` -
        `authentik_sources_ldap.ldapsource` - `authentik_sources_ldap.ldapsourcepropertymapping` -
        `authentik_sources_oauth.oauthsource` - `authentik_sources_oauth.oauthsourcepropertymapping` -
        `authentik_sources_oauth.useroauthsourceconnection` - `authentik_sources_oauth.groupoauthsourceconnection` -
        `authentik_sources_plex.plexsource` - `authentik_sources_plex.plexsourcepropertymapping` -
        `authentik_sources_plex.userplexsourceconnection` - `authentik_sources_plex.groupplexsourceconnection` -
        `authentik_sources_saml.samlsource` - `authentik_sources_saml.samlsourcepropertymapping` -
        `authentik_sources_saml.usersamlsourceconnection` - `authentik_sources_saml.groupsamlsourceconnection` -
        `authentik_sources_scim.scimsource` - `authentik_sources_scim.scimsourcepropertymapping` -
        `authentik_stages_authenticator_duo.authenticatorduostage` - `authentik_stages_authenticator_duo.duodevice` -
        `authentik_stages_authenticator_sms.authenticatorsmsstage` - `authentik_stages_authenticator_sms.smsdevice` -
        `authentik_stages_authenticator_static.authenticatorstaticstage` - `authentik_stages_authenticator_static.staticdevice`
        - `authentik_stages_authenticator_totp.authenticatortotpstage` - `authentik_stages_authenticator_totp.totpdevice` -
        `authentik_stages_authenticator_validate.authenticatorvalidatestage` -
        `authentik_stages_authenticator_webauthn.authenticatorwebauthnstage` -
        `authentik_stages_authenticator_webauthn.webauthndevice` - `authentik_stages_captcha.captchastage` -
        `authentik_stages_consent.consentstage` - `authentik_stages_consent.userconsent` - `authentik_stages_deny.denystage` -
        `authentik_stages_dummy.dummystage` - `authentik_stages_email.emailstage` -
        `authentik_stages_identification.identificationstage` - `authentik_stages_invitation.invitationstage` -
        `authentik_stages_invitation.invitation` - `authentik_stages_password.passwordstage` - `authentik_stages_prompt.prompt`
        - `authentik_stages_prompt.promptstage` - `authentik_stages_user_delete.userdeletestage` -
        `authentik_stages_user_login.userloginstage` - `authentik_stages_user_logout.userlogoutstage` -
        `authentik_stages_user_write.userwritestage` - `authentik_brands.brand` - `authentik_blueprints.blueprintinstance` -
        `authentik_core.group` - `authentik_core.user` - `authentik_core.application` - `authentik_core.token` -
        `authentik_enterprise.license` - `authentik_providers_google_workspace.googleworkspaceprovider` -
        `authentik_providers_google_workspace.googleworkspaceprovidermapping` -
        `authentik_providers_microsoft_entra.microsoftentraprovider` -
        `authentik_providers_microsoft_entra.microsoftentraprovidermapping` - `authentik_providers_rac.racprovider` -
        `authentik_providers_rac.endpoint` - `authentik_providers_rac.racpropertymapping` -
        `authentik_stages_authenticator_endpoint_gdtc.authenticatorendpointgdtcstage` - `authentik_stages_source.sourcestage` -
        `authentik_events.event` - `authentik_events.notificationtransport` - `authentik_events.notification` -
        `authentik_events.notificationrule` - `authentik_events.notificationwebhookmapping`
        """
        return pulumi.get(self, "model")

    @model.setter
    def model(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "model", value)

    @property
    @pulumi.getter(name="objectId")
    def object_id(self) -> Optional[pulumi.Input[str]]:
        return pulumi.get(self, "object_id")

    @object_id.setter
    def object_id(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "object_id", value)

    @property
    @pulumi.getter(name="rbacPermissionUserId")
    def rbac_permission_user_id(self) -> Optional[pulumi.Input[str]]:
        return pulumi.get(self, "rbac_permission_user_id")

    @rbac_permission_user_id.setter
    def rbac_permission_user_id(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "rbac_permission_user_id", value)


@pulumi.input_type
class _RbacPermissionUserState:
    def __init__(__self__, *,
                 model: Optional[pulumi.Input[str]] = None,
                 object_id: Optional[pulumi.Input[str]] = None,
                 permission: Optional[pulumi.Input[str]] = None,
                 rbac_permission_user_id: Optional[pulumi.Input[str]] = None,
                 user: Optional[pulumi.Input[float]] = None):
        """
        Input properties used for looking up and filtering RbacPermissionUser resources.
        :param pulumi.Input[str] model: Allowed values: - `authentik_tenants.domain` - `authentik_crypto.certificatekeypair` - `authentik_flows.flow` -
               `authentik_flows.flowstagebinding` - `authentik_outposts.dockerserviceconnection` -
               `authentik_outposts.kubernetesserviceconnection` - `authentik_outposts.outpost` - `authentik_policies_dummy.dummypolicy`
               - `authentik_policies_event_matcher.eventmatcherpolicy` - `authentik_policies_expiry.passwordexpirypolicy` -
               `authentik_policies_expression.expressionpolicy` - `authentik_policies_geoip.geoippolicy` -
               `authentik_policies_password.passwordpolicy` - `authentik_policies_reputation.reputationpolicy` -
               `authentik_policies.policybinding` - `authentik_providers_ldap.ldapprovider` - `authentik_providers_oauth2.scopemapping`
               - `authentik_providers_oauth2.oauth2provider` - `authentik_providers_proxy.proxyprovider` -
               `authentik_providers_radius.radiusprovider` - `authentik_providers_radius.radiusproviderpropertymapping` -
               `authentik_providers_saml.samlprovider` - `authentik_providers_saml.samlpropertymapping` -
               `authentik_providers_scim.scimprovider` - `authentik_providers_scim.scimmapping` - `authentik_rbac.role` -
               `authentik_sources_kerberos.kerberossource` - `authentik_sources_kerberos.kerberossourcepropertymapping` -
               `authentik_sources_kerberos.userkerberossourceconnection` - `authentik_sources_kerberos.groupkerberossourceconnection` -
               `authentik_sources_ldap.ldapsource` - `authentik_sources_ldap.ldapsourcepropertymapping` -
               `authentik_sources_oauth.oauthsource` - `authentik_sources_oauth.oauthsourcepropertymapping` -
               `authentik_sources_oauth.useroauthsourceconnection` - `authentik_sources_oauth.groupoauthsourceconnection` -
               `authentik_sources_plex.plexsource` - `authentik_sources_plex.plexsourcepropertymapping` -
               `authentik_sources_plex.userplexsourceconnection` - `authentik_sources_plex.groupplexsourceconnection` -
               `authentik_sources_saml.samlsource` - `authentik_sources_saml.samlsourcepropertymapping` -
               `authentik_sources_saml.usersamlsourceconnection` - `authentik_sources_saml.groupsamlsourceconnection` -
               `authentik_sources_scim.scimsource` - `authentik_sources_scim.scimsourcepropertymapping` -
               `authentik_stages_authenticator_duo.authenticatorduostage` - `authentik_stages_authenticator_duo.duodevice` -
               `authentik_stages_authenticator_sms.authenticatorsmsstage` - `authentik_stages_authenticator_sms.smsdevice` -
               `authentik_stages_authenticator_static.authenticatorstaticstage` - `authentik_stages_authenticator_static.staticdevice`
               - `authentik_stages_authenticator_totp.authenticatortotpstage` - `authentik_stages_authenticator_totp.totpdevice` -
               `authentik_stages_authenticator_validate.authenticatorvalidatestage` -
               `authentik_stages_authenticator_webauthn.authenticatorwebauthnstage` -
               `authentik_stages_authenticator_webauthn.webauthndevice` - `authentik_stages_captcha.captchastage` -
               `authentik_stages_consent.consentstage` - `authentik_stages_consent.userconsent` - `authentik_stages_deny.denystage` -
               `authentik_stages_dummy.dummystage` - `authentik_stages_email.emailstage` -
               `authentik_stages_identification.identificationstage` - `authentik_stages_invitation.invitationstage` -
               `authentik_stages_invitation.invitation` - `authentik_stages_password.passwordstage` - `authentik_stages_prompt.prompt`
               - `authentik_stages_prompt.promptstage` - `authentik_stages_user_delete.userdeletestage` -
               `authentik_stages_user_login.userloginstage` - `authentik_stages_user_logout.userlogoutstage` -
               `authentik_stages_user_write.userwritestage` - `authentik_brands.brand` - `authentik_blueprints.blueprintinstance` -
               `authentik_core.group` - `authentik_core.user` - `authentik_core.application` - `authentik_core.token` -
               `authentik_enterprise.license` - `authentik_providers_google_workspace.googleworkspaceprovider` -
               `authentik_providers_google_workspace.googleworkspaceprovidermapping` -
               `authentik_providers_microsoft_entra.microsoftentraprovider` -
               `authentik_providers_microsoft_entra.microsoftentraprovidermapping` - `authentik_providers_rac.racprovider` -
               `authentik_providers_rac.endpoint` - `authentik_providers_rac.racpropertymapping` -
               `authentik_stages_authenticator_endpoint_gdtc.authenticatorendpointgdtcstage` - `authentik_stages_source.sourcestage` -
               `authentik_events.event` - `authentik_events.notificationtransport` - `authentik_events.notification` -
               `authentik_events.notificationrule` - `authentik_events.notificationwebhookmapping`
        """
        if model is not None:
            pulumi.set(__self__, "model", model)
        if object_id is not None:
            pulumi.set(__self__, "object_id", object_id)
        if permission is not None:
            pulumi.set(__self__, "permission", permission)
        if rbac_permission_user_id is not None:
            pulumi.set(__self__, "rbac_permission_user_id", rbac_permission_user_id)
        if user is not None:
            pulumi.set(__self__, "user", user)

    @property
    @pulumi.getter
    def model(self) -> Optional[pulumi.Input[str]]:
        """
        Allowed values: - `authentik_tenants.domain` - `authentik_crypto.certificatekeypair` - `authentik_flows.flow` -
        `authentik_flows.flowstagebinding` - `authentik_outposts.dockerserviceconnection` -
        `authentik_outposts.kubernetesserviceconnection` - `authentik_outposts.outpost` - `authentik_policies_dummy.dummypolicy`
        - `authentik_policies_event_matcher.eventmatcherpolicy` - `authentik_policies_expiry.passwordexpirypolicy` -
        `authentik_policies_expression.expressionpolicy` - `authentik_policies_geoip.geoippolicy` -
        `authentik_policies_password.passwordpolicy` - `authentik_policies_reputation.reputationpolicy` -
        `authentik_policies.policybinding` - `authentik_providers_ldap.ldapprovider` - `authentik_providers_oauth2.scopemapping`
        - `authentik_providers_oauth2.oauth2provider` - `authentik_providers_proxy.proxyprovider` -
        `authentik_providers_radius.radiusprovider` - `authentik_providers_radius.radiusproviderpropertymapping` -
        `authentik_providers_saml.samlprovider` - `authentik_providers_saml.samlpropertymapping` -
        `authentik_providers_scim.scimprovider` - `authentik_providers_scim.scimmapping` - `authentik_rbac.role` -
        `authentik_sources_kerberos.kerberossource` - `authentik_sources_kerberos.kerberossourcepropertymapping` -
        `authentik_sources_kerberos.userkerberossourceconnection` - `authentik_sources_kerberos.groupkerberossourceconnection` -
        `authentik_sources_ldap.ldapsource` - `authentik_sources_ldap.ldapsourcepropertymapping` -
        `authentik_sources_oauth.oauthsource` - `authentik_sources_oauth.oauthsourcepropertymapping` -
        `authentik_sources_oauth.useroauthsourceconnection` - `authentik_sources_oauth.groupoauthsourceconnection` -
        `authentik_sources_plex.plexsource` - `authentik_sources_plex.plexsourcepropertymapping` -
        `authentik_sources_plex.userplexsourceconnection` - `authentik_sources_plex.groupplexsourceconnection` -
        `authentik_sources_saml.samlsource` - `authentik_sources_saml.samlsourcepropertymapping` -
        `authentik_sources_saml.usersamlsourceconnection` - `authentik_sources_saml.groupsamlsourceconnection` -
        `authentik_sources_scim.scimsource` - `authentik_sources_scim.scimsourcepropertymapping` -
        `authentik_stages_authenticator_duo.authenticatorduostage` - `authentik_stages_authenticator_duo.duodevice` -
        `authentik_stages_authenticator_sms.authenticatorsmsstage` - `authentik_stages_authenticator_sms.smsdevice` -
        `authentik_stages_authenticator_static.authenticatorstaticstage` - `authentik_stages_authenticator_static.staticdevice`
        - `authentik_stages_authenticator_totp.authenticatortotpstage` - `authentik_stages_authenticator_totp.totpdevice` -
        `authentik_stages_authenticator_validate.authenticatorvalidatestage` -
        `authentik_stages_authenticator_webauthn.authenticatorwebauthnstage` -
        `authentik_stages_authenticator_webauthn.webauthndevice` - `authentik_stages_captcha.captchastage` -
        `authentik_stages_consent.consentstage` - `authentik_stages_consent.userconsent` - `authentik_stages_deny.denystage` -
        `authentik_stages_dummy.dummystage` - `authentik_stages_email.emailstage` -
        `authentik_stages_identification.identificationstage` - `authentik_stages_invitation.invitationstage` -
        `authentik_stages_invitation.invitation` - `authentik_stages_password.passwordstage` - `authentik_stages_prompt.prompt`
        - `authentik_stages_prompt.promptstage` - `authentik_stages_user_delete.userdeletestage` -
        `authentik_stages_user_login.userloginstage` - `authentik_stages_user_logout.userlogoutstage` -
        `authentik_stages_user_write.userwritestage` - `authentik_brands.brand` - `authentik_blueprints.blueprintinstance` -
        `authentik_core.group` - `authentik_core.user` - `authentik_core.application` - `authentik_core.token` -
        `authentik_enterprise.license` - `authentik_providers_google_workspace.googleworkspaceprovider` -
        `authentik_providers_google_workspace.googleworkspaceprovidermapping` -
        `authentik_providers_microsoft_entra.microsoftentraprovider` -
        `authentik_providers_microsoft_entra.microsoftentraprovidermapping` - `authentik_providers_rac.racprovider` -
        `authentik_providers_rac.endpoint` - `authentik_providers_rac.racpropertymapping` -
        `authentik_stages_authenticator_endpoint_gdtc.authenticatorendpointgdtcstage` - `authentik_stages_source.sourcestage` -
        `authentik_events.event` - `authentik_events.notificationtransport` - `authentik_events.notification` -
        `authentik_events.notificationrule` - `authentik_events.notificationwebhookmapping`
        """
        return pulumi.get(self, "model")

    @model.setter
    def model(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "model", value)

    @property
    @pulumi.getter(name="objectId")
    def object_id(self) -> Optional[pulumi.Input[str]]:
        return pulumi.get(self, "object_id")

    @object_id.setter
    def object_id(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "object_id", value)

    @property
    @pulumi.getter
    def permission(self) -> Optional[pulumi.Input[str]]:
        return pulumi.get(self, "permission")

    @permission.setter
    def permission(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "permission", value)

    @property
    @pulumi.getter(name="rbacPermissionUserId")
    def rbac_permission_user_id(self) -> Optional[pulumi.Input[str]]:
        return pulumi.get(self, "rbac_permission_user_id")

    @rbac_permission_user_id.setter
    def rbac_permission_user_id(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "rbac_permission_user_id", value)

    @property
    @pulumi.getter
    def user(self) -> Optional[pulumi.Input[float]]:
        return pulumi.get(self, "user")

    @user.setter
    def user(self, value: Optional[pulumi.Input[float]]):
        pulumi.set(self, "user", value)


class RbacPermissionUser(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 model: Optional[pulumi.Input[str]] = None,
                 object_id: Optional[pulumi.Input[str]] = None,
                 permission: Optional[pulumi.Input[str]] = None,
                 rbac_permission_user_id: Optional[pulumi.Input[str]] = None,
                 user: Optional[pulumi.Input[float]] = None,
                 __props__=None):
        """
        Create a RbacPermissionUser resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[str] model: Allowed values: - `authentik_tenants.domain` - `authentik_crypto.certificatekeypair` - `authentik_flows.flow` -
               `authentik_flows.flowstagebinding` - `authentik_outposts.dockerserviceconnection` -
               `authentik_outposts.kubernetesserviceconnection` - `authentik_outposts.outpost` - `authentik_policies_dummy.dummypolicy`
               - `authentik_policies_event_matcher.eventmatcherpolicy` - `authentik_policies_expiry.passwordexpirypolicy` -
               `authentik_policies_expression.expressionpolicy` - `authentik_policies_geoip.geoippolicy` -
               `authentik_policies_password.passwordpolicy` - `authentik_policies_reputation.reputationpolicy` -
               `authentik_policies.policybinding` - `authentik_providers_ldap.ldapprovider` - `authentik_providers_oauth2.scopemapping`
               - `authentik_providers_oauth2.oauth2provider` - `authentik_providers_proxy.proxyprovider` -
               `authentik_providers_radius.radiusprovider` - `authentik_providers_radius.radiusproviderpropertymapping` -
               `authentik_providers_saml.samlprovider` - `authentik_providers_saml.samlpropertymapping` -
               `authentik_providers_scim.scimprovider` - `authentik_providers_scim.scimmapping` - `authentik_rbac.role` -
               `authentik_sources_kerberos.kerberossource` - `authentik_sources_kerberos.kerberossourcepropertymapping` -
               `authentik_sources_kerberos.userkerberossourceconnection` - `authentik_sources_kerberos.groupkerberossourceconnection` -
               `authentik_sources_ldap.ldapsource` - `authentik_sources_ldap.ldapsourcepropertymapping` -
               `authentik_sources_oauth.oauthsource` - `authentik_sources_oauth.oauthsourcepropertymapping` -
               `authentik_sources_oauth.useroauthsourceconnection` - `authentik_sources_oauth.groupoauthsourceconnection` -
               `authentik_sources_plex.plexsource` - `authentik_sources_plex.plexsourcepropertymapping` -
               `authentik_sources_plex.userplexsourceconnection` - `authentik_sources_plex.groupplexsourceconnection` -
               `authentik_sources_saml.samlsource` - `authentik_sources_saml.samlsourcepropertymapping` -
               `authentik_sources_saml.usersamlsourceconnection` - `authentik_sources_saml.groupsamlsourceconnection` -
               `authentik_sources_scim.scimsource` - `authentik_sources_scim.scimsourcepropertymapping` -
               `authentik_stages_authenticator_duo.authenticatorduostage` - `authentik_stages_authenticator_duo.duodevice` -
               `authentik_stages_authenticator_sms.authenticatorsmsstage` - `authentik_stages_authenticator_sms.smsdevice` -
               `authentik_stages_authenticator_static.authenticatorstaticstage` - `authentik_stages_authenticator_static.staticdevice`
               - `authentik_stages_authenticator_totp.authenticatortotpstage` - `authentik_stages_authenticator_totp.totpdevice` -
               `authentik_stages_authenticator_validate.authenticatorvalidatestage` -
               `authentik_stages_authenticator_webauthn.authenticatorwebauthnstage` -
               `authentik_stages_authenticator_webauthn.webauthndevice` - `authentik_stages_captcha.captchastage` -
               `authentik_stages_consent.consentstage` - `authentik_stages_consent.userconsent` - `authentik_stages_deny.denystage` -
               `authentik_stages_dummy.dummystage` - `authentik_stages_email.emailstage` -
               `authentik_stages_identification.identificationstage` - `authentik_stages_invitation.invitationstage` -
               `authentik_stages_invitation.invitation` - `authentik_stages_password.passwordstage` - `authentik_stages_prompt.prompt`
               - `authentik_stages_prompt.promptstage` - `authentik_stages_user_delete.userdeletestage` -
               `authentik_stages_user_login.userloginstage` - `authentik_stages_user_logout.userlogoutstage` -
               `authentik_stages_user_write.userwritestage` - `authentik_brands.brand` - `authentik_blueprints.blueprintinstance` -
               `authentik_core.group` - `authentik_core.user` - `authentik_core.application` - `authentik_core.token` -
               `authentik_enterprise.license` - `authentik_providers_google_workspace.googleworkspaceprovider` -
               `authentik_providers_google_workspace.googleworkspaceprovidermapping` -
               `authentik_providers_microsoft_entra.microsoftentraprovider` -
               `authentik_providers_microsoft_entra.microsoftentraprovidermapping` - `authentik_providers_rac.racprovider` -
               `authentik_providers_rac.endpoint` - `authentik_providers_rac.racpropertymapping` -
               `authentik_stages_authenticator_endpoint_gdtc.authenticatorendpointgdtcstage` - `authentik_stages_source.sourcestage` -
               `authentik_events.event` - `authentik_events.notificationtransport` - `authentik_events.notification` -
               `authentik_events.notificationrule` - `authentik_events.notificationwebhookmapping`
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: RbacPermissionUserArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a RbacPermissionUser resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param RbacPermissionUserArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(RbacPermissionUserArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 model: Optional[pulumi.Input[str]] = None,
                 object_id: Optional[pulumi.Input[str]] = None,
                 permission: Optional[pulumi.Input[str]] = None,
                 rbac_permission_user_id: Optional[pulumi.Input[str]] = None,
                 user: Optional[pulumi.Input[float]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = RbacPermissionUserArgs.__new__(RbacPermissionUserArgs)

            __props__.__dict__["model"] = model
            __props__.__dict__["object_id"] = object_id
            if permission is None and not opts.urn:
                raise TypeError("Missing required property 'permission'")
            __props__.__dict__["permission"] = permission
            __props__.__dict__["rbac_permission_user_id"] = rbac_permission_user_id
            if user is None and not opts.urn:
                raise TypeError("Missing required property 'user'")
            __props__.__dict__["user"] = user
        super(RbacPermissionUser, __self__).__init__(
            'authentik:index/rbacPermissionUser:RbacPermissionUser',
            resource_name,
            __props__,
            opts,
            package_ref=_utilities.get_package())

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            model: Optional[pulumi.Input[str]] = None,
            object_id: Optional[pulumi.Input[str]] = None,
            permission: Optional[pulumi.Input[str]] = None,
            rbac_permission_user_id: Optional[pulumi.Input[str]] = None,
            user: Optional[pulumi.Input[float]] = None) -> 'RbacPermissionUser':
        """
        Get an existing RbacPermissionUser resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[str] model: Allowed values: - `authentik_tenants.domain` - `authentik_crypto.certificatekeypair` - `authentik_flows.flow` -
               `authentik_flows.flowstagebinding` - `authentik_outposts.dockerserviceconnection` -
               `authentik_outposts.kubernetesserviceconnection` - `authentik_outposts.outpost` - `authentik_policies_dummy.dummypolicy`
               - `authentik_policies_event_matcher.eventmatcherpolicy` - `authentik_policies_expiry.passwordexpirypolicy` -
               `authentik_policies_expression.expressionpolicy` - `authentik_policies_geoip.geoippolicy` -
               `authentik_policies_password.passwordpolicy` - `authentik_policies_reputation.reputationpolicy` -
               `authentik_policies.policybinding` - `authentik_providers_ldap.ldapprovider` - `authentik_providers_oauth2.scopemapping`
               - `authentik_providers_oauth2.oauth2provider` - `authentik_providers_proxy.proxyprovider` -
               `authentik_providers_radius.radiusprovider` - `authentik_providers_radius.radiusproviderpropertymapping` -
               `authentik_providers_saml.samlprovider` - `authentik_providers_saml.samlpropertymapping` -
               `authentik_providers_scim.scimprovider` - `authentik_providers_scim.scimmapping` - `authentik_rbac.role` -
               `authentik_sources_kerberos.kerberossource` - `authentik_sources_kerberos.kerberossourcepropertymapping` -
               `authentik_sources_kerberos.userkerberossourceconnection` - `authentik_sources_kerberos.groupkerberossourceconnection` -
               `authentik_sources_ldap.ldapsource` - `authentik_sources_ldap.ldapsourcepropertymapping` -
               `authentik_sources_oauth.oauthsource` - `authentik_sources_oauth.oauthsourcepropertymapping` -
               `authentik_sources_oauth.useroauthsourceconnection` - `authentik_sources_oauth.groupoauthsourceconnection` -
               `authentik_sources_plex.plexsource` - `authentik_sources_plex.plexsourcepropertymapping` -
               `authentik_sources_plex.userplexsourceconnection` - `authentik_sources_plex.groupplexsourceconnection` -
               `authentik_sources_saml.samlsource` - `authentik_sources_saml.samlsourcepropertymapping` -
               `authentik_sources_saml.usersamlsourceconnection` - `authentik_sources_saml.groupsamlsourceconnection` -
               `authentik_sources_scim.scimsource` - `authentik_sources_scim.scimsourcepropertymapping` -
               `authentik_stages_authenticator_duo.authenticatorduostage` - `authentik_stages_authenticator_duo.duodevice` -
               `authentik_stages_authenticator_sms.authenticatorsmsstage` - `authentik_stages_authenticator_sms.smsdevice` -
               `authentik_stages_authenticator_static.authenticatorstaticstage` - `authentik_stages_authenticator_static.staticdevice`
               - `authentik_stages_authenticator_totp.authenticatortotpstage` - `authentik_stages_authenticator_totp.totpdevice` -
               `authentik_stages_authenticator_validate.authenticatorvalidatestage` -
               `authentik_stages_authenticator_webauthn.authenticatorwebauthnstage` -
               `authentik_stages_authenticator_webauthn.webauthndevice` - `authentik_stages_captcha.captchastage` -
               `authentik_stages_consent.consentstage` - `authentik_stages_consent.userconsent` - `authentik_stages_deny.denystage` -
               `authentik_stages_dummy.dummystage` - `authentik_stages_email.emailstage` -
               `authentik_stages_identification.identificationstage` - `authentik_stages_invitation.invitationstage` -
               `authentik_stages_invitation.invitation` - `authentik_stages_password.passwordstage` - `authentik_stages_prompt.prompt`
               - `authentik_stages_prompt.promptstage` - `authentik_stages_user_delete.userdeletestage` -
               `authentik_stages_user_login.userloginstage` - `authentik_stages_user_logout.userlogoutstage` -
               `authentik_stages_user_write.userwritestage` - `authentik_brands.brand` - `authentik_blueprints.blueprintinstance` -
               `authentik_core.group` - `authentik_core.user` - `authentik_core.application` - `authentik_core.token` -
               `authentik_enterprise.license` - `authentik_providers_google_workspace.googleworkspaceprovider` -
               `authentik_providers_google_workspace.googleworkspaceprovidermapping` -
               `authentik_providers_microsoft_entra.microsoftentraprovider` -
               `authentik_providers_microsoft_entra.microsoftentraprovidermapping` - `authentik_providers_rac.racprovider` -
               `authentik_providers_rac.endpoint` - `authentik_providers_rac.racpropertymapping` -
               `authentik_stages_authenticator_endpoint_gdtc.authenticatorendpointgdtcstage` - `authentik_stages_source.sourcestage` -
               `authentik_events.event` - `authentik_events.notificationtransport` - `authentik_events.notification` -
               `authentik_events.notificationrule` - `authentik_events.notificationwebhookmapping`
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _RbacPermissionUserState.__new__(_RbacPermissionUserState)

        __props__.__dict__["model"] = model
        __props__.__dict__["object_id"] = object_id
        __props__.__dict__["permission"] = permission
        __props__.__dict__["rbac_permission_user_id"] = rbac_permission_user_id
        __props__.__dict__["user"] = user
        return RbacPermissionUser(resource_name, opts=opts, __props__=__props__)

    @property
    @pulumi.getter
    def model(self) -> pulumi.Output[Optional[str]]:
        """
        Allowed values: - `authentik_tenants.domain` - `authentik_crypto.certificatekeypair` - `authentik_flows.flow` -
        `authentik_flows.flowstagebinding` - `authentik_outposts.dockerserviceconnection` -
        `authentik_outposts.kubernetesserviceconnection` - `authentik_outposts.outpost` - `authentik_policies_dummy.dummypolicy`
        - `authentik_policies_event_matcher.eventmatcherpolicy` - `authentik_policies_expiry.passwordexpirypolicy` -
        `authentik_policies_expression.expressionpolicy` - `authentik_policies_geoip.geoippolicy` -
        `authentik_policies_password.passwordpolicy` - `authentik_policies_reputation.reputationpolicy` -
        `authentik_policies.policybinding` - `authentik_providers_ldap.ldapprovider` - `authentik_providers_oauth2.scopemapping`
        - `authentik_providers_oauth2.oauth2provider` - `authentik_providers_proxy.proxyprovider` -
        `authentik_providers_radius.radiusprovider` - `authentik_providers_radius.radiusproviderpropertymapping` -
        `authentik_providers_saml.samlprovider` - `authentik_providers_saml.samlpropertymapping` -
        `authentik_providers_scim.scimprovider` - `authentik_providers_scim.scimmapping` - `authentik_rbac.role` -
        `authentik_sources_kerberos.kerberossource` - `authentik_sources_kerberos.kerberossourcepropertymapping` -
        `authentik_sources_kerberos.userkerberossourceconnection` - `authentik_sources_kerberos.groupkerberossourceconnection` -
        `authentik_sources_ldap.ldapsource` - `authentik_sources_ldap.ldapsourcepropertymapping` -
        `authentik_sources_oauth.oauthsource` - `authentik_sources_oauth.oauthsourcepropertymapping` -
        `authentik_sources_oauth.useroauthsourceconnection` - `authentik_sources_oauth.groupoauthsourceconnection` -
        `authentik_sources_plex.plexsource` - `authentik_sources_plex.plexsourcepropertymapping` -
        `authentik_sources_plex.userplexsourceconnection` - `authentik_sources_plex.groupplexsourceconnection` -
        `authentik_sources_saml.samlsource` - `authentik_sources_saml.samlsourcepropertymapping` -
        `authentik_sources_saml.usersamlsourceconnection` - `authentik_sources_saml.groupsamlsourceconnection` -
        `authentik_sources_scim.scimsource` - `authentik_sources_scim.scimsourcepropertymapping` -
        `authentik_stages_authenticator_duo.authenticatorduostage` - `authentik_stages_authenticator_duo.duodevice` -
        `authentik_stages_authenticator_sms.authenticatorsmsstage` - `authentik_stages_authenticator_sms.smsdevice` -
        `authentik_stages_authenticator_static.authenticatorstaticstage` - `authentik_stages_authenticator_static.staticdevice`
        - `authentik_stages_authenticator_totp.authenticatortotpstage` - `authentik_stages_authenticator_totp.totpdevice` -
        `authentik_stages_authenticator_validate.authenticatorvalidatestage` -
        `authentik_stages_authenticator_webauthn.authenticatorwebauthnstage` -
        `authentik_stages_authenticator_webauthn.webauthndevice` - `authentik_stages_captcha.captchastage` -
        `authentik_stages_consent.consentstage` - `authentik_stages_consent.userconsent` - `authentik_stages_deny.denystage` -
        `authentik_stages_dummy.dummystage` - `authentik_stages_email.emailstage` -
        `authentik_stages_identification.identificationstage` - `authentik_stages_invitation.invitationstage` -
        `authentik_stages_invitation.invitation` - `authentik_stages_password.passwordstage` - `authentik_stages_prompt.prompt`
        - `authentik_stages_prompt.promptstage` - `authentik_stages_user_delete.userdeletestage` -
        `authentik_stages_user_login.userloginstage` - `authentik_stages_user_logout.userlogoutstage` -
        `authentik_stages_user_write.userwritestage` - `authentik_brands.brand` - `authentik_blueprints.blueprintinstance` -
        `authentik_core.group` - `authentik_core.user` - `authentik_core.application` - `authentik_core.token` -
        `authentik_enterprise.license` - `authentik_providers_google_workspace.googleworkspaceprovider` -
        `authentik_providers_google_workspace.googleworkspaceprovidermapping` -
        `authentik_providers_microsoft_entra.microsoftentraprovider` -
        `authentik_providers_microsoft_entra.microsoftentraprovidermapping` - `authentik_providers_rac.racprovider` -
        `authentik_providers_rac.endpoint` - `authentik_providers_rac.racpropertymapping` -
        `authentik_stages_authenticator_endpoint_gdtc.authenticatorendpointgdtcstage` - `authentik_stages_source.sourcestage` -
        `authentik_events.event` - `authentik_events.notificationtransport` - `authentik_events.notification` -
        `authentik_events.notificationrule` - `authentik_events.notificationwebhookmapping`
        """
        return pulumi.get(self, "model")

    @property
    @pulumi.getter(name="objectId")
    def object_id(self) -> pulumi.Output[Optional[str]]:
        return pulumi.get(self, "object_id")

    @property
    @pulumi.getter
    def permission(self) -> pulumi.Output[str]:
        return pulumi.get(self, "permission")

    @property
    @pulumi.getter(name="rbacPermissionUserId")
    def rbac_permission_user_id(self) -> pulumi.Output[str]:
        return pulumi.get(self, "rbac_permission_user_id")

    @property
    @pulumi.getter
    def user(self) -> pulumi.Output[float]:
        return pulumi.get(self, "user")

